![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

# 1.
my_array = np.arange(10)
print(my_array)

# 2.
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [2]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


In [6]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [7]:
print(my_array)
print(my_array[-8::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


In [29]:
my_array[0:3][:-4:-1]
print(my_array[0:3][::-1])
print(my_array[0:3][::-1][::2])

[2 1 0]
[2 0]


In [ ]:
my_array2 = my_array[0:3]
my_array3 = my_array2[::-1]

In [24]:
my_array[[2, 0, 3]] # fancy accessing

array([2, 0, 3])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [30]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
print(my_matrix[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [35]:
print(my_matrix[::-1])
np.flip(my_matrix)

[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [36]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
my_matrix[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [38]:
my_matrix = np.arange(1, 21).reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
my_matrix[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [40]:
print(my_matrix[::, ::-1])
print(my_matrix[:-1:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [41]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Metodo 1
mask = np.array([True, False, False, True, False])
mask = x == "Loro"

x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [43]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [46]:
np.extract(x == "Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [47]:
x = np.arange(20).reshape((2,5,2))
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [48]:
import numpy as np

x = np.zeros(10)
print(x)

print(x.itemsize) # Cada elemento
print(x.nbytes) # El array entero

x[3] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [49]:
x = np.arange(10, 50)
print(x)
print(x[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [50]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [51]:
x = np.random.randint(1, 100, size = (10,10))
print(x)

print(x.min())
print(x.max())

[[26 88 22 93 49 11 25 17 19 74]
 [30 72 34 68 75 49 38 98 69  3]
 [10 53 17 59 73 98 76 12 17 98]
 [ 1  5 66 85 25 61 18 62 30 89]
 [49 53 20 27 17 82 54 17 97 65]
 [53 90 74 52 31 21 50 18 28 33]
 [14 32 15 53  5 30 60 36 91 10]
 [31 21 78 77 75 21 36 51 97 86]
 [14  9 36 71 62 58 41 87 92 99]
 [53 43 38 58 33 56 84 90 96 80]]
1
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [52]:
x = np.random.random(30)
m = x.mean()
print(m)

0.5486629248613712


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [53]:
x = np.ones((10,10))
x[1:-1:, 1:-1:] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [56]:
x = np.zeros((10,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
x = np.zeros((10,10))
x[0:10:9] = 1
x.T[0:10:9] = 1
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [59]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [60]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [64]:
x = np.random.randint(1, 20, (5,5))

x = (x - np.mean(x))/np.std(x)

print(x)

[[ 0.88354777  0.52143803  0.52143803 -1.10805581 -0.20278146]
 [ 1.24565752 -0.74594607  1.24565752  0.34038316 -0.38383633]
 [-0.20278146 -0.38383633 -0.02172658 -0.02172658 -0.02172658]
 [-0.74594607  1.06460264  1.24565752  1.06460264  1.06460264]
 [-1.8322753  -2.01333017 -1.28911068 -1.47016556  1.24565752]]


In [80]:
x = np.random.randint(1, 20, (5,5))
x

array([[15,  3,  1, 18, 14],
       [13,  3,  2, 12,  4],
       [13,  3,  5, 10, 13],
       [11,  2, 14, 17,  8],
       [12,  6, 19, 14,  9]])

In [85]:
np.mean(x)

9.64

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [89]:
x = np.arange(11)
print(x)

y = x.copy()
y[(y > 3) & (y <= 8)] *= -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [88]:
x = np.arange(11)
y = x.copy()

x[4:9] *= -1 
print(y)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [5]:
import numpy as np

tablero = np.full(fill_value = " ", shape = (10, 10))
tablero[0:2, 1] = "O"
tablero[1, 3:7] = "O"
tablero[0,1] = "X"
tablero[0,0] = "-"
tablero


array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [6]:
eslora = 4
import random

while True:
    # "N" - "S" - "E" - "O"
    orient = random.choice(["N", "S", "E", "O"])
    
    # Posicion inicial del barco
    current_pos = np.random.randint(10, size = 2)
    
    fila = current_pos[0]
    col = current_pos[1]
    
    # Recogemos las 4 posiciones colindantes a current_pos
    coors_posiS = tablero[fila: fila+eslora,col]
    coors_posiE = tablero[fila,col:col+eslora]
    coors_posiN = tablero[fila: fila-eslora:-1,col]
    coors_posiO = tablero[fila,col:col-eslora:-1]
    
    # comprobamos si esas posiciones son validas
    # orientacion norte
    
    if orient == "N" and 0<= fila - eslora < 10 and "O" not in coors_posiN:
        tablero[fila:fila-eslora:-1, col] = "O"
        break
    # Orientacion Este
    elif orient == 'E' and 0 <= col + eslora < 10 and 'O' not in coors_posiE:
        tablero[fila, col: col + eslora] = 'O'
        break

    # Orientacion Sur
    elif orient == 'S' and 0 <= fila + eslora < 10 and 'O' not in coors_posiS:
        tablero[fila:fila + eslora, col] = 'O'
        break

    # Orientacion Oeste
    elif orient == 'O' and 0 <= col - eslora < 10 and 'O' not in coors_posiO:
        tablero[fila, col: col - eslora:-1] = 'O'
        break

    # No cumple con las dimensiones del tablero, o hay un barco ahi
    # Probamos con otra coordenada
    else:
        continue
tablero
    
    

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')